"use client";

import { RotateCcw, Copy, Check } from "lucide-react";
import { useClipboard } from "@/hooks/useClipboard";
import type { RoastResult } from "@/types/torched";

interface ActionRowProps {
  roast: RoastResult;
  onReset: () => void;
}

function buildRoastText(roast: RoastResult): string {
  return [
    `TORCHED RESULTS`,
    `Overall Score: ${roast.overallScore}/100`,
    `Verdict: ${roast.verdict}`,
    ``,
    `CATEGORIES`,
    `Design: ${roast.categories.design.score}/100 — ${roast.categories.design.roast}`,
    `Copy: ${roast.categories.copy.score}/100 — ${roast.categories.copy.roast}`,
    `UX: ${roast.categories.ux.score}/100 — ${roast.categories.ux.roast}`,
    `Vibe: ${roast.categories.vibe.score}/100 — ${roast.categories.vibe.roast}`,
    ``,
    `THE ROAST`,
    roast.fullRoast,
    ``,
    `ISSUES`,
    ...roast.issues.map((i) => `• ${i.title}: ${i.description}`),
    ``,
    `ONE GOOD THING`,
    roast.oneGoodThing,
    ``,
    `QUICK WINS`,
    ...roast.quickWins.map((w, i) => `${i + 1}. ${w}`),
    ``,
    `Generated by Torched — torched.app`,
  ].join("\n");
}

export default function ActionRow({ roast, onReset }: ActionRowProps) {
  const { copied, copy } = useClipboard();

  return (
    <div className="flex flex-col sm:flex-row gap-3 pt-4">
      <button
        onClick={onReset}
        className="flex items-center justify-center gap-2 bg-yellow-400 hover:bg-accent-hover text-black font-bold rounded-lg px-6 py-3 transition-colors text-sm"
      >
        <RotateCcw className="w-4 h-4" />
        Roast Another Site
      </button>
      <button
        onClick={() => copy(buildRoastText(roast))}
        className="flex items-center justify-center gap-2 border border-yellow-400 text-yellow-400 hover:bg-yellow-400/10 font-bold rounded-lg px-6 py-3 transition-colors text-sm"
      >
        {copied ? (
          <>
            <Check className="w-4 h-4" />
            Copied!
          </>
        ) : (
          <>
            <Copy className="w-4 h-4" />
            Copy Roast
          </>
        )}
      </button>
    </div>
  );
}
